servo_dt: 0.00125

ip_address: "tcp://127.0.0.1:5557"

b_sim: true ## if false, all the "exp_" parameters are used

wbc:
  task:
    com_task:
      com_feedback_source: 0 # 0: com feedback / 1: dcm feedback
      com_height_target_source: 0 # 0: com height / 1: base height

      ## sim params
      weight : [20., 20., 20.]
      kp : [200., 200., 200.]
      kd : [10., 10., 5.]
      icp_weight : [20., 20., 20.] # only used when feedback source : 1
      icp_kp : [10., 10., 100.]
      icp_kd : [0., 0., 5.] # x, y will be ignored
      icp_ki : [0.1, 0.1, 0.1] 
      time_constant : 5.

      ## exp params
      exp_weight : [20., 20., 20.]
      exp_kp : [200., 200., 200.]
      exp_kd : [10., 10., 5.]
      exp_icp_weight : [20., 20., 20.] # only used when feedback source : 1
      exp_icp_kp : [10., 10., 100.]
      exp_icp_kd : [0., 0., 5.] # x, y will be ignored
      exp_icp_ki : [0.1, 0.1, 0.1] 
      exp_time_constant : 5.

    torso_ori_task:
      ## sim params
      weight : [20., 20., 2.]
      kp : [100., 100., 100.]
      kd : [10., 10., 10.]

      ## exp params
      exp_weight : [20., 20., 2.]
      exp_kp : [100., 100., 100.]
      exp_kd : [10., 10., 10.]

    upper_body_task:
      ## sim params
      ## l_shoulder_fe(0), l_shoulder_aa(1), l_shoulder_ie(2), l_elbow_fe(3), l_wrist_ps_(4),
      ## l_wrist_pitch(5), neck_pitch(6), r_shoulder_fe(7), r_shoulder_aa(8), r_shoulder_ie(9),
      ## r_shoulder_ie(10), r_elbow_fe(11), r_wrist_ps(12), r_wrist_pitch(13)
      weight : [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.]
      kp : [100., 100., 100., 50., 40., 40., 100., 100., 100., 100., 50., 40., 40.]
      kd : [8., 8., 8., 3., 2., 2., 10., 8., 8., 8., 3., 2., 2.]

      ## exp params
      exp_weight : [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.]
      exp_kp : [10., 10., 10., 7., 5., 5., 5., 10., 10., 10., 7., 5., 5.]
      exp_kd : [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]


state_machine:
    initialize:
      init_duration: 4.
      target_joint_pos: [0., 0., -0.785, 0.785, 0.785, -0.785, 0., 0., 0.523, 0., -1.57, 0., 0., 0., 0., 0., -0.785, 0.785, 0.785, -0.785, 0., 0., -0.523, 0., -1.57, 0., 0.] #pinocchio robotsystem joint order

    stand_up:
      standup_duration: 1.
      target_com_height: 0.7
      target_base_height: 0.9
